### PR TITLE
Update STUN/TURN listener documentation

### PR DESCRIPTION
**Pull request by weiss**
- Suggest non-standard STUN/TURN port.
- Don't suggest DNS discovery for STUN/TURN.
- Fix STUNS/TURNS configuration example.

### CODE REVIEW

**Comment by licaon-kter** [comment]
maybe add a comment explaining why you changed it and that admins are encouraged to use some other instead, so not all new configs end up on the (new) default :)

**Comment by weiss** [comment]
> maybe add a comment explaining why you changed it and that admins are encouraged to use some other instead, so not all new configs end up on the (new) default :)

I wouldn't bother new admins with the fact that the example port is now different from the past (and/or from the 'standard' port), why would they care.  (Should probably be mentioned in ejabberd's change log though.)

For the same reason (keep it simple), I decided against encouraging admins to use yet another port.  I was assuming federated XMPP/ejabberd is too niche to be discovered by script kiddies, and that we can reconsider once world-domination is achieved.

Might be wrong, PRs welcome I guess :grin:

**Comment by badlop** [comment]
Thanks!

I've annotated myself that the next ejabberd release notes should include this recommendation.

**Comment by badlop** [comment]
The release notes will include something like this, ok?

> Use non-standard STUN port
>
> STUN via UDP can easily be abused for reflection/amplification DDoS attacks. For this reason, the example `ejabberd.yml` file included with ejabberd will now use a non-standard port to make it harder for attackers to discover the service in ejabberd.yml.example.
>
> Modern XMPP clients discover the port via XEP-0215, so there's no advantage in sticking to the standard port.

**Comment by weiss** [comment]
@badlop, perfect, thank you! 👍🏻

**Pull request merged**
