### PR TITLE
Fix sip example URIs

### PR DESCRIPTION
**Pull request by licaon-kter**
I guess

### CODE REVIEW

**Comment by badlop** [comment]
Right, the " are missing. On the other hand, it appears those ;lr are required, as they are in the default options values, and also in previous code.

**Comment by zinid** [comment]
Yes, ";lr" are required, don't remove them.

**Comment by licaon-kter** [comment]
Thanks

**Comment by badlop** [comment]
Ok, then I've just added the ". Thanks for reporting!

**Pull request closed without merging**
